---
- hosts: all
  remote_user: qaadm
  become: yes
  become_user: root
  gather_facts: false
  tasks:
    - name: Validando se o bin√°rio existe no servidor remoto
      include: tasks/bin_version.yml app_name_extracao={{ item }}
      with_items: "{{ app_name.split('|') }}"
